# These are supported funding model platforms

github: [smashah]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: smashah
tidelift: npm/@open-wa/wa-automate
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: smashah
otechie: smashah
custom: ['https://www.buymeacoffee.com/smashah', 'https://gum.co/BTMt']
