name: 🐞 Bug report
description: Create a report to help us improve
labels: [Bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Are you using the latest version of the library?
    description: This is not like most libraries where older versions can remain functioning forever. Sometimes major updates from WA result in a new version of this library being released which then becomes essentially the minimum working version.
    options:
    - label: I have checked and am using the latest version of the library.
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: dropdown
  attributes:
    label: Mode
    description: How are you using the library while experiencing this bug?
    multiple: false
    options:
      - EASY API/CLI
      - My own code
  validations:
    required: true
- type: textarea
  attributes:
    label: create() code
    description: |
      This is the code you use to create the client. e.g
      ```javascript
      create(...)
      ```
    render: markdown
  validations:
    required: false
    
- type: textarea
  attributes:
    label: DEBUG INFO
    description: |
      This is the info printed to the console when you start your app. It should look like this:
      ```
      Debug Info {
        WA_VERSION: ...,
        PAGE_UA: ...,
        WA_AUTOMATE_VERSION: ...,
        BROWSER_VERSION: ...
      }
      ```
    render: markdown
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Node**: 13.14.0
        - **npm**: 7.6.3
    value: |
        - OS: 
        - Node: 
        - npm: 
    render: markdown
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Screenshots
    description: |
      If applicable, add screenshots to help explain your problem.
      
      Tip:  Use ```headless: false``` to get screenshots
  validations:
    required: false
    
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
  validations:
    required: false
